# This file configures github.com/golangci/golangci-lint.
version: '2'
run:
  tests: true
linters:
  default: none
  enable:
    - bidichk
    - copyloopvar
    - durationcheck
    - gocheckcompilerdirectives
    - govet
    - ineffassign
    - mirror
    - misspell
    - reassign
    - revive
    - staticcheck
    - unconvert
    - unused
    - usetesting
    - whitespace
  settings:
    staticcheck:
      checks:
        # disable Quickfixes
        - -QF1*
    revive:
      enable-all-rules: false
      # here we enable specific useful rules
      # see https://golangci-lint.run/usage/linters/#revive for supported rules
      rules:
        - name: receiver-naming
          severity: warning
          disabled: false
          exclude:
            - ''
formatters:
  enable:
    - goimports
  settings:
    gofmt:
      simplify: true
