# The compose file is only for building images

version: '3.8'

services:
  dtl:
    image: metisdao/dtl:${VERSION:-dev}
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile
      target: data-transport-layer

  relayer:
    image: metisdao/relayer:${VERSION:-dev}
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile
      target: message-relayer

  batch-submitter:
    image: metisdao/batch-submitter:${VERSION:-dev}
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile
      target: batch-submitter

  l2geth:
    image: metisdao/l2geth:${VERSION:-dev}
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.geth
